"""engie-nl: async client for the private API behind the ENGIE Energie NL app."""

from .auth import BrowserLogin, EmailChallenge, OktaAuth, TokenSet, make_pkce_pair
from .client import EngieClient
from .exceptions import (
    EngieApiError,
    EngieAuthError,
    EngieEmailCodeRequired,
    EngieError,
    EngieMfaRequiredError,
    EngieNetworkError,
)
from .models import (
    Consumption,
    ConsumptionSeries,
    DayAheadPrice,
    DeliveryAddress,
    DocumentRef,
    EnergyType,
    EstimationCosts,
    Mandate,
    MerPeriod,
    MeteringPoint,
    MeterReadings,
    OutageMessage,
    ProductInfo,
    Reading,
    Register,
    Tariffs,
    Transaction,
    TransactionStatus,
    User,
)

__version__ = "0.1.0"

__all__ = [
    "__version__",
    "BrowserLogin",
    "EmailChallenge",
    "OktaAuth",
    "TokenSet",
    "make_pkce_pair",
    "EngieClient",
    "EngieApiError",
    "EngieAuthError",
    "EngieEmailCodeRequired",
    "EngieError",
    "EngieMfaRequiredError",
    "EngieNetworkError",
    "Consumption",
    "ConsumptionSeries",
    "DayAheadPrice",
    "DeliveryAddress",
    "DocumentRef",
    "EnergyType",
    "EstimationCosts",
    "Mandate",
    "MerPeriod",
    "MeteringPoint",
    "MeterReadings",
    "OutageMessage",
    "ProductInfo",
    "Reading",
    "Register",
    "Tariffs",
    "Transaction",
    "TransactionStatus",
    "User",
]
